# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Set user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Add suffix to version on PR with prerelease
        if: github.event_name == 'pull_request' && github.head_ref != 'master' && github.head_ref != 'main'
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          npm version prerelease --preid=${BRANCH_NAME}-${{github.sha}}-prerelease
          npm config set //npm.pkg.github.com/:_authToken ${{secrets.GITHUB_TOKEN}}
          echo "---------------- config ----------------"
          npm config list
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Run release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{secrets.GITHUB_TOKEN}}
          echo "---------------- config ----------------"
          npm config list
          npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
