# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish-npm:
    uses: seeliang/Github-shared-flow/.github/workflows/npm-publish-github-packages.yml@main
    with:
      branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      commit_sha: ${{ github.event_name == 'pull_request' && github.sha }}
