# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package publish

on:
  push:
    branches:
      - master
      - "feature-**"

jobs:
  publish-npm:
    uses: seeliang/Github-shared-flow/.github/workflows/npm-publish-github-packages.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
