# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package publish

on:
  push:
    branches:
      - master
      - reuse-workflow 
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  npm-publish:
    uses: seeliang/Github-shared-flow/.github/workflows/npm-publish-github-packages.yml@semantic-on-release-branch
    with:
      branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }} 
      commit_sha: ${{ github.sha }}